AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - lambda-sgl-api-parceiros-processor-test-1.0-SNAPSHOT
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
    - '*/*'
Resources:
  LambdaSglApiParceirosProcessorTest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: s3://quarkus-lambda-maxback/d99946bcb1b170e66bce83ebaabb3973
      MemorySize: 256
      Timeout: 15
      Policies: AWSLambdaBasicExecutionRole
    Metadata:
      SamResourceId: LambdaSglApiParceirosProcessorTest
